#!/usr/bin/env bash

# 20200803 - put all 3ddeconvolve nodata outputs (norm std dev)
# into a datatable. each row is a seed. columns are norm std dev of X.mat and contrasts
set -euo pipefail
cd $(dirname $0)
for phase in DD OD ID SOA; do
   for d in seeded/$phase/tr*/; do
      find $d -maxdepth 2 -mindepth 2 -type f -iname 'convolve.txt' |
       xargs perl -MFile::Basename=dirname -lne '
        $key=$2 if /(Gen|Stim).*: ([^ ]*)/;
        $h{dirname($ARGV)}{"${key}_$1"}=$2 if /^\W+(LC|h).*=.*?([0-9.]+)/;
        END{
          @vals=sort (keys %{$h{(keys %h)[0]}});
          print join("\t","file",@vals);
          for my $f (keys %h){
            %_h = %{$h{$f}};
            print join("\t",$f, @_h{@vals} )
          }
    }'| sort -k6n |uniq > ${d%/}.txt
   done
done
